In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("invoice.csv")
print(df)

   Invoice_ID          Vendor_Name Invoice_Date    Amount        Category  \
0      INV001    CloudNine Pvt Ltd   2026-06-29  364000.0     Maintenance
1      INV002    CloudNine Pvt Ltd   2026-03-16  184800.0          Travel
2      INV003         DataCore Ltd   2026-05-10  189000.0      Consulting
3      INV004     ABC Technologies   2026-08-07  302500.0      Consulting
4      INV005     Nova Enterprises   2026-03-05   70875.0  Cloud Services
5      INV006     Zenith Solutions   2026-05-12   99000.0        Hardware
6      INV007     Zenith Solutions   2026-03-25  336000.0      Consulting
7      INV008     ABC Technologies   2026-06-13   22000.0          Travel
8      INV009    BlueWave Services   2026-07-10   11000.0        Hardware
9      INV010         DataCore Ltd   2026-02-09   82500.0     Maintenance
10     INV011     ABC Technologies   2026-06-06   34125.0        Software
11     INV012          PQR Systems   2026-03-22   67200.0        Software
12     INV013     Zenith Solutions   2026-02-10  315000.0      Consulting
13     INV014     Nova Enterprises   2026-04-14   50400.0        Software
14     INV015    BlueWave Services   2026-08-06  192500.0  Cloud Services
15     INV016     Nova Enterprises   2026-07-24   84000.0        Software
16     INV017    BlueWave Services   2026-05-31  117600.0  Cloud Services
17     INV018          PQR Systems   2026-03-27   66000.0     Maintenance
18     INV019     Nova Enterprises   2026-01-28  132000.0          Travel
19     INV020     Nova Enterprises   2026-08-05  147000.0        Software
20     INV021     Zenith Solutions   2026-05-12   99000.0        Software
21     INV022     Zenith Solutions   2026-05-12   99000.0          Travel
22     INV023         DataCore Ltd   2026-07-05   44000.0        Hardware
23     INV024  SmartEdge Solutions   2026-03-22   30250.0        Hardware
24     INV025     ABC Technologies   2026-05-27   73500.0      Consulting
25     INV026          PQR Systems   2026-07-03   30800.0          Travel
26     INV027         DataCore Ltd   2026-08-02  288750.0        Software
27     INV028     Nova Enterprises   2026-07-06   33000.0  Cloud Services
28     INV029     Nova Enterprises   2026-06-10  220000.0        Software
29     INV030     Zenith Solutions   2026-05-31   78400.0      Consulting
30     INV031     Zenith Solutions   2026-05-09  147000.0     Maintenance
31     INV032          PQR Systems   2026-05-27   33000.0        Software
32     INV033  SmartEdge Solutions   2026-06-13   66000.0  Cloud Services
33     INV034     ABC Technologies   2026-04-03   44000.0        Hardware
34     INV035     Nova Enterprises   2026-06-10   11000.0     Maintenance
35     INV036  SmartEdge Solutions   2026-02-02  100800.0          Travel
36     INV037         DataCore Ltd   2026-01-08   90750.0     Maintenance
37     INV038  SmartEdge Solutions   2026-07-16  201600.0      Consulting
38     INV039     Nova Enterprises   2026-08-08  231000.0     Maintenance
39     INV040    BlueWave Services   2026-01-24   35750.0     Maintenance
40     INV041     Nova Enterprises   2026-07-10  175000.0        Software
41     INV042     Zenith Solutions   2026-02-23  225000.0        Hardware
42     INV043          PQR Systems   2026-05-10   26250.0        Software
43     INV044    CloudNine Pvt Ltd   2026-01-26   15750.0     Maintenance
44     INV045     Nova Enterprises   2026-03-06  176000.0      Consulting
45     INV046     Zenith Solutions   2026-02-01  192500.0  Cloud Services
46     INV047     Zenith Solutions   2026-02-27   16500.0          Travel
47     INV048     ABC Technologies   2026-01-08   52500.0      Consulting
48     INV049    CloudNine Pvt Ltd   2026-04-09   73500.0             NaN
49     INV050  SmartEdge Solutions   2026-03-04   33000.0        Hardware
50     INV051    CloudNine Pvt Ltd   2026-05-07   94500.0        Software
51     INV052     Zenith Solutions   2026-04-06  294000.0     Maintenance
52     INV053  SmartEdge Solutions   2026-07-10  105000.0  Cloud Services
53     INV054         DataCore Ltd   2026-07-04  273000.0        Software
54     INV055     Nova Enterprises   2026-05-24   52500.0      Consulting
55     INV056     Zenith Solutions   2026-01-10   99000.0      Consulting
56     INV057     Zenith Solutions   2026-04-06   15750.0      Consulting
57     INV058     Nova Enterprises   2026-05-08  121000.0  Cloud Services
58     INV059          PQR Systems   2026-06-20   56000.0        Software
59     INV060     Nova Enterprises   2026-01-29  145600.0          Travel

   Payment_Status  Quantity  Unit_Price      Tax  Department Payment_Method
0         Pending        13       25000  39000.0     Finance    Credit Card
1            Paid        11       15000  19800.0  Operations            UPI
2         Pending        12       15000   9000.0       Sales  Bank Transfer
3        Rejected        11       25000  27500.0          HR    Credit Card
4         Pending         9        7500   3375.0          IT    Credit Card
5            Paid         9       10000   9000.0     Finance  Bank Transfer
6            Paid        12       25000  36000.0          HR            UPI
7            Paid         2       10000   2000.0     Finance            UPI
8         Pending         2        5000   1000.0  Operations  Bank Transfer
9         Pending         5       15000   7500.0          IT  Bank Transfer
10        Pending        13        2500   1625.0  Operations    Credit Card
11        Pending         8        7500   7200.0     Finance    Credit Card
12           Paid        12       25000  15000.0         NaN    Credit Card
13           Paid         6        7500   5400.0          HR  Bank Transfer
14           Paid         7       25000  17500.0     Finance            UPI
15           Paid         3       25000   9000.0  Operations            UPI
16           Paid         7       15000  12600.0       Sales    Credit Card
17           Paid        12        5000   6000.0       Sales            UPI
18           Paid        12       10000  12000.0     Finance    Credit Card
19           Paid         7       20000   7000.0          IT  Bank Transfer
20           Paid         7       20000  16800.0          IT    Credit Card
21           Paid         8       25000  24000.0          IT  Bank Transfer
22        Pending         4       10000   4000.0       Sales  Bank Transfer
23           Paid        11        2500   2750.0       Sales  Bank Transfer
24           Paid        14        5000   3500.0  Operations    Credit Card
25           Paid        11        2500   3300.0  Operations            UPI
26           Paid        11       25000  13750.0       Sales    Credit Card
27        Pending         4        7500   3000.0  Operations            NaN
28        Pending         8       25000  20000.0          IT  Bank Transfer
29           Paid        14        5000   8400.0          IT  Bank Transfer
30        Pending        14       10000   7000.0          IT  Bank Transfer
31        Pending         3       10000   3000.0          HR  Bank Transfer
32           Paid         6       10000   6000.0          IT    Credit Card
33        Pending         2       20000   4000.0       Sales  Bank Transfer
34           Paid         4        2500   1000.0          HR  Bank Transfer
35           Paid        12        7500  10800.0       Sales    Credit Card
36           Paid        11        7500   8250.0  Operations    Credit Card
37           Paid        12       15000  21600.0          IT  Bank Transfer
38        Pending        14       15000  21000.0  Operations  Bank Transfer
39        Pending        13        2500   3250.0  Operations  Bank Transfer
40           Paid        13       15000  23400.0     Finance  Bank Transfer
41        Pending        10        7500   7500.0     Finance    Credit Card
42        Pending        10        2500   1250.0       Sales            UPI
43           Paid         3        5000    750.0          IT  Bank Transfer
44        Pending         8       20000  16000.0  Operations            UPI
45           Paid         7       25000  17500.0       Sales            UPI
46           Paid         6        2500   1500.0          HR  Bank Transfer
47        Pending         5       10000   2500.0  Operations            UPI
48           Paid         7       10000   3500.0          HR  Bank Transfer
49           Paid         3       10000   3000.0       Sales            UPI
50           Paid         9       10000   4500.0          IT    Credit Card
51           Paid        14       20000  14000.0       Sales    Credit Card
52           Paid         5       20000   5000.0          HR  Bank Transfer
53           Paid        13       20000  13000.0  Operations  Bank Transfer
54           Paid        10        5000   2500.0       Sales    Credit Card
55           Paid         6       15000   9000.0     Finance    Credit Card
56        Pending         1       15000    750.0     Finance  Bank Transfer
57        Pending        11       10000  11000.0          IT  Bank Transfer
58       Rejected         5       10000   6000.0     Finance    Credit Card
59           Paid        13       10000  15600.0          HR            UPI

In [3]:
df.head()

,Invoice_ID,Vendor_Name,Invoice_Date,Amount,Category,Payment_Status,Quantity,Unit_Price,Tax,Department,Payment_Method
0,INV001,CloudNine Pvt Ltd,2026-06-29,364000.0,Maintenance,Pending,13,25000,39000.0,Finance,Credit Card
1,INV002,CloudNine Pvt Ltd,2026-03-16,184800.0,Travel,Paid,11,15000,19800.0,Operations,UPI
2,INV003,DataCore Ltd,2026-05-10,189000.0,Consulting,Pending,12,15000,9000.0,Sales,Bank Transfer
3,INV004,ABC Technologies,2026-08-07,302500.0,Consulting,Rejected,11,25000,27500.0,HR,Credit Card
4,INV005,Nova Enterprises,2026-03-05,70875.0,Cloud Services,Pending,9,7500,3375.0,IT,Credit Card

In [4]:
df.tail()

,Invoice_ID,Vendor_Name,Invoice_Date,Amount,Category,Payment_Status,Quantity,Unit_Price,Tax,Department,Payment_Method
55,INV056,Zenith Solutions,2026-01-10,99000.0,Consulting,Paid,6,15000,9000.0,Finance,Credit Card
56,INV057,Zenith Solutions,2026-04-06,15750.0,Consulting,Pending,1,15000,750.0,Finance,Bank Transfer
57,INV058,Nova Enterprises,2026-05-08,121000.0,Cloud Services,Pending,11,10000,11000.0,IT,Bank Transfer
58,INV059,PQR Systems,2026-06-20,56000.0,Software,Rejected,5,10000,6000.0,Finance,Credit Card
59,INV060,Nova Enterprises,2026-01-29,145600.0,Travel,Paid,13,10000,15600.0,HR,UPI

In [5]:
df.shape

(60, 11)

In [6]:
df.columns

Index(['Invoice_ID', 'Vendor_Name', 'Invoice_Date', 'Amount', 'Category',
       'Payment_Status', 'Quantity', 'Unit_Price', 'Tax', 'Department',
       'Payment_Method'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Invoice_ID      60 non-null     object
 1   Vendor_Name     60 non-null     object
 2   Invoice_Date    60 non-null     object
 3   Amount          60 non-null     float64
 4   Category        59 non-null     object
 5   Payment_Status  60 non-null     object
 6   Quantity        60 non-null     int64
 7   Unit_Price      60 non-null     int64
 8   Tax             60 non-null     float64
 9   Department      59 non-null     object
 10  Payment_Method  59 non-null     object
dtypes: float64(2), int64(2), object(7)
memory usage: 5.3+ KB

In [8]:
df.describe()

              Amount   Quantity   Unit_Price           Tax
count      60.000000  60.000000     60.00000     60.000000
mean   117790.833333   8.583333  12750.00000   9852.500000
std     92822.726406   3.823618   7488.69204   8579.659998
min     11000.000000   1.000000   2500.00000    750.000000
25%     44000.000000   5.750000   7500.00000   3287.500000
50%     92625.000000   9.000000  10000.00000   7350.000000
75%    178200.000000  12.000000  20000.00000  14250.000000
max    364000.000000  14.000000  25000.00000  39000.000000

In [9]:
df.isnull().sum()

Invoice_ID        0
Vendor_Name       0
Invoice_Date      0
Amount            0
Category          1
Payment_Status    0
Quantity          0
Unit_Price        0
Tax               0
Department        1
Payment_Method    1
dtype: int64

In [10]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
dtype: bool

In [11]:
df=df.drop_duplicates()
print(df)

   Invoice_ID          Vendor_Name Invoice_Date    Amount        Category  \
0      INV001    CloudNine Pvt Ltd   2026-06-29  364000.0     Maintenance
1      INV002    CloudNine Pvt Ltd   2026-03-16  184800.0          Travel
2      INV003         DataCore Ltd   2026-05-10  189000.0      Consulting
3      INV004     ABC Technologies   2026-08-07  302500.0      Consulting
4      INV005     Nova Enterprises   2026-03-05   70875.0  Cloud Services
5      INV006     Zenith Solutions   2026-05-12   99000.0        Hardware
6      INV007     Zenith Solutions   2026-03-25  336000.0      Consulting
7      INV008     ABC Technologies   2026-06-13   22000.0          Travel
8      INV009    BlueWave Services   2026-07-10   11000.0        Hardware
9      INV010         DataCore Ltd   2026-02-09   82500.0     Maintenance
10     INV011     ABC Technologies   2026-06-06   34125.0        Software
11     INV012          PQR Systems   2026-03-22   67200.0        Software
12     INV013     Zenith Solutions   2026-02-10  315000.0      Consulting
13     INV014     Nova Enterprises   2026-04-14   50400.0        Software
14     INV015    BlueWave Services   2026-08-06  192500.0  Cloud Services
15     INV016     Nova Enterprises   2026-07-24   84000.0        Software
16     INV017    BlueWave Services   2026-05-31  117600.0  Cloud Services
17     INV018          PQR Systems   2026-03-27   66000.0     Maintenance
18     INV019     Nova Enterprises   2026-01-28  132000.0          Travel
19     INV020     Nova Enterprises   2026-08-05  147000.0        Software
20     INV021     Zenith Solutions   2026-05-12   99000.0        Software
21     INV022     Zenith Solutions   2026-05-12   99000.0          Travel
22     INV023         DataCore Ltd   2026-07-05   44000.0        Hardware
23     INV024  SmartEdge Solutions   2026-03-22   30250.0        Hardware
24     INV025     ABC Technologies   2026-05-27   73500.0      Consulting
25     INV026          PQR Systems   2026-07-03   30800.0          Travel
26     INV027         DataCore Ltd   2026-08-02  288750.0        Software
27     INV028     Nova Enterprises   2026-07-06   33000.0  Cloud Services
28     INV029     Nova Enterprises   2026-06-10  220000.0        Software
29     INV030     Zenith Solutions   2026-05-31   78400.0      Consulting
30     INV031     Zenith Solutions   2026-05-09  147000.0     Maintenance
31     INV032          PQR Systems   2026-05-27   33000.0        Software
32     INV033  SmartEdge Solutions   2026-06-13   66000.0  Cloud Services
33     INV034     ABC Technologies   2026-04-03   44000.0        Hardware
34     INV035     Nova Enterprises   2026-06-10   11000.0     Maintenance
35     INV036  SmartEdge Solutions   2026-02-02  100800.0          Travel
36     INV037         DataCore Ltd   2026-01-08   90750.0     Maintenance
37     INV038  SmartEdge Solutions   2026-07-16  201600.0      Consulting
38     INV039     Nova Enterprises   2026-08-08  231000.0     Maintenance
39     INV040    BlueWave Services   2026-01-24   35750.0     Maintenance
40     INV041     Nova Enterprises   2026-07-10  175000.0        Software
41     INV042     Zenith Solutions   2026-02-23  225000.0        Hardware
42     INV043          PQR Systems   2026-05-10   26250.0        Software
43     INV044    CloudNine Pvt Ltd   2026-01-26   15750.0     Maintenance
44     INV045     Nova Enterprises   2026-03-06  176000.0      Consulting
45     INV046     Zenith Solutions   2026-02-01  192500.0  Cloud Services
46     INV047     Zenith Solutions   2026-02-27   16500.0          Travel
47     INV048     ABC Technologies   2026-01-08   52500.0      Consulting
48     INV049    CloudNine Pvt Ltd   2026-04-09   73500.0             NaN
49     INV050  SmartEdge Solutions   2026-03-04   33000.0        Hardware
50     INV051    CloudNine Pvt Ltd   2026-05-07   94500.0        Software
51     INV052     Zenith Solutions   2026-04-06  294000.0     Maintenance
52     INV053  SmartEdge Solutions   2026-07-10  105000.0  Cloud Services
53     INV054         DataCore Ltd   2026-07-04  273000.0        Software
54     INV055     Nova Enterprises   2026-05-24   52500.0      Consulting
55     INV056     Zenith Solutions   2026-01-10   99000.0      Consulting
56     INV057     Zenith Solutions   2026-04-06   15750.0      Consulting
57     INV058     Nova Enterprises   2026-05-08  121000.0  Cloud Services
58     INV059          PQR Systems   2026-06-20   56000.0        Software
59     INV060     Nova Enterprises   2026-01-29  145600.0          Travel

   Payment_Status  Quantity  Unit_Price      Tax  Department Payment_Method
0         Pending        13       25000  39000.0     Finance    Credit Card
1            Paid        11       15000  19800.0  Operations            UPI
2         Pending        12       15000   9000.0       Sales  Bank Transfer
3        Rejected        11       25000  27500.0          HR    Credit Card
4         Pending         9        7500   3375.0          IT    Credit Card
5            Paid         9       10000   9000.0     Finance  Bank Transfer
6            Paid        12       25000  36000.0          HR            UPI
7            Paid         2       10000   2000.0     Finance            UPI
8         Pending         2        5000   1000.0  Operations  Bank Transfer
9         Pending         5       15000   7500.0          IT  Bank Transfer
10        Pending        13        2500   1625.0  Operations    Credit Card
11        Pending         8        7500   7200.0     Finance    Credit Card
12           Paid        12       25000  15000.0         NaN    Credit Card
13           Paid         6        7500   5400.0          HR  Bank Transfer
14           Paid         7       25000  17500.0     Finance            UPI
15           Paid         3       25000   9000.0  Operations            UPI
16           Paid         7       15000  12600.0       Sales    Credit Card
17           Paid        12        5000   6000.0       Sales            UPI
18           Paid        12       10000  12000.0     Finance    Credit Card
19           Paid         7       20000   7000.0          IT  Bank Transfer
20           Paid         7       20000  16800.0          IT    Credit Card
21           Paid         8       25000  24000.0          IT  Bank Transfer
22        Pending         4       10000   4000.0       Sales  Bank Transfer
23           Paid        11        2500   2750.0       Sales  Bank Transfer
24           Paid        14        5000   3500.0  Operations    Credit Card
25           Paid        11        2500   3300.0  Operations            UPI
26           Paid        11       25000  13750.0       Sales    Credit Card
27        Pending         4        7500   3000.0  Operations            NaN
28        Pending         8       25000  20000.0          IT  Bank Transfer
29           Paid        14        5000   8400.0          IT  Bank Transfer
30        Pending        14       10000   7000.0          IT  Bank Transfer
31        Pending         3       10000   3000.0          HR  Bank Transfer
32           Paid         6       10000   6000.0          IT    Credit Card
33        Pending         2       20000   4000.0       Sales  Bank Transfer
34           Paid         4        2500   1000.0          HR  Bank Transfer
35           Paid        12        7500  10800.0       Sales    Credit Card
36           Paid        11        7500   8250.0  Operations    Credit Card
37           Paid        12       15000  21600.0          IT  Bank Transfer
38        Pending        14       15000  21000.0  Operations  Bank Transfer
39        Pending        13        2500   3250.0  Operations  Bank Transfer
40           Paid        13       15000  23400.0     Finance  Bank Transfer
41        Pending        10        7500   7500.0     Finance    Credit Card
42        Pending        10        2500   1250.0       Sales            UPI
43           Paid         3        5000    750.0          IT  Bank Transfer
44        Pending         8       20000  16000.0  Operations            UPI
45           Paid         7       25000  17500.0       Sales            UPI
46           Paid         6        2500   1500.0          HR  Bank Transfer
47        Pending         5       10000   2500.0  Operations            UPI
48           Paid         7       10000   3500.0          HR  Bank Transfer
49           Paid         3       10000   3000.0       Sales            UPI
50           Paid         9       10000   4500.0          IT    Credit Card
51           Paid        14       20000  14000.0       Sales    Credit Card
52           Paid         5       20000   5000.0          HR  Bank Transfer
53           Paid        13       20000  13000.0  Operations  Bank Transfer
54           Paid        10        5000   2500.0       Sales    Credit Card
55           Paid         6       15000   9000.0     Finance    Credit Card
56        Pending         1       15000    750.0     Finance  Bank Transfer
57        Pending        11       10000  11000.0          IT  Bank Transfer
58       Rejected         5       10000   6000.0     Finance    Credit Card
59           Paid        13       10000  15600.0          HR            UPI

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Invoice_ID      60 non-null     object
 1   Vendor_Name     60 non-null     object
 2   Invoice_Date    60 non-null     object
 3   Amount          60 non-null     float64
 4   Category        59 non-null     object
 5   Payment_Status  60 non-null     object
 6   Quantity        60 non-null     int64
 7   Unit_Price      60 non-null     int64
 8   Tax             60 non-null     float64
 9   Department      59 non-null     object
 10  Payment_Method  59 non-null     object
dtypes: float64(2), int64(2), object(7)
memory usage: 5.3+ KB

In [13]:
df["Invoice_Date"]=pd.to_datetime(df["Invoice_Date"])
print(df)

   Invoice_ID          Vendor_Name Invoice_Date    Amount        Category  \
0      INV001    CloudNine Pvt Ltd   2026-06-29  364000.0     Maintenance
1      INV002    CloudNine Pvt Ltd   2026-03-16  184800.0          Travel
2      INV003         DataCore Ltd   2026-05-10  189000.0      Consulting
3      INV004     ABC Technologies   2026-08-07  302500.0      Consulting
4      INV005     Nova Enterprises   2026-03-05   70875.0  Cloud Services
5      INV006     Zenith Solutions   2026-05-12   99000.0        Hardware
6      INV007     Zenith Solutions   2026-03-25  336000.0      Consulting
7      INV008     ABC Technologies   2026-06-13   22000.0          Travel
8      INV009    BlueWave Services   2026-07-10   11000.0        Hardware
9      INV010         DataCore Ltd   2026-02-09   82500.0     Maintenance
10     INV011     ABC Technologies   2026-06-06   34125.0        Software
11     INV012          PQR Systems   2026-03-22   67200.0        Software
12     INV013     Zenith Solutions   2026-02-10  315000.0      Consulting
13     INV014     Nova Enterprises   2026-04-14   50400.0        Software
14     INV015    BlueWave Services   2026-08-06  192500.0  Cloud Services
15     INV016     Nova Enterprises   2026-07-24   84000.0        Software
16     INV017    BlueWave Services   2026-05-31  117600.0  Cloud Services
17     INV018          PQR Systems   2026-03-27   66000.0     Maintenance
18     INV019     Nova Enterprises   2026-01-28  132000.0          Travel
19     INV020     Nova Enterprises   2026-08-05  147000.0        Software
20     INV021     Zenith Solutions   2026-05-12   99000.0        Software
21     INV022     Zenith Solutions   2026-05-12   99000.0          Travel
22     INV023         DataCore Ltd   2026-07-05   44000.0        Hardware
23     INV024  SmartEdge Solutions   2026-03-22   30250.0        Hardware
24     INV025     ABC Technologies   2026-05-27   73500.0      Consulting
25     INV026          PQR Systems   2026-07-03   30800.0          Travel
26     INV027         DataCore Ltd   2026-08-02  288750.0        Software
27     INV028     Nova Enterprises   2026-07-06   33000.0  Cloud Services
28     INV029     Nova Enterprises   2026-06-10  220000.0        Software
29     INV030     Zenith Solutions   2026-05-31   78400.0      Consulting
30     INV031     Zenith Solutions   2026-05-09  147000.0     Maintenance
31     INV032          PQR Systems   2026-05-27   33000.0        Software
32     INV033  SmartEdge Solutions   2026-06-13   66000.0  Cloud Services
33     INV034     ABC Technologies   2026-04-03   44000.0        Hardware
34     INV035     Nova Enterprises   2026-06-10   11000.0     Maintenance
35     INV036  SmartEdge Solutions   2026-02-02  100800.0          Travel
36     INV037         DataCore Ltd   2026-01-08   90750.0     Maintenance
37     INV038  SmartEdge Solutions   2026-07-16  201600.0      Consulting
38     INV039     Nova Enterprises   2026-08-08  231000.0     Maintenance
39     INV040    BlueWave Services   2026-01-24   35750.0     Maintenance
40     INV041     Nova Enterprises   2026-07-10  175000.0        Software
41     INV042     Zenith Solutions   2026-02-23  225000.0        Hardware
42     INV043          PQR Systems   2026-05-10   26250.0        Software
43     INV044    CloudNine Pvt Ltd   2026-01-26   15750.0     Maintenance
44     INV045     Nova Enterprises   2026-03-06  176000.0      Consulting
45     INV046     Zenith Solutions   2026-02-01  192500.0  Cloud Services
46     INV047     Zenith Solutions   2026-02-27   16500.0          Travel
47     INV048     ABC Technologies   2026-01-08   52500.0      Consulting
48     INV049    CloudNine Pvt Ltd   2026-04-09   73500.0             NaN
49     INV050  SmartEdge Solutions   2026-03-04   33000.0        Hardware
50     INV051    CloudNine Pvt Ltd   2026-05-07   94500.0        Software
51     INV052     Zenith Solutions   2026-04-06  294000.0     Maintenance
52     INV053  SmartEdge Solutions   2026-07-10  105000.0  Cloud Services
53     INV054         DataCore Ltd   2026-07-04  273000.0        Software
54     INV055     Nova Enterprises   2026-05-24   52500.0      Consulting
55     INV056     Zenith Solutions   2026-01-10   99000.0      Consulting
56     INV057     Zenith Solutions   2026-04-06   15750.0      Consulting
57     INV058     Nova Enterprises   2026-05-08  121000.0  Cloud Services
58     INV059          PQR Systems   2026-06-20   56000.0        Software
59     INV060     Nova Enterprises   2026-01-29  145600.0          Travel

   Payment_Status  Quantity  Unit_Price      Tax  Department Payment_Method
0         Pending        13       25000  39000.0     Finance    Credit Card
1            Paid        11       15000  19800.0  Operations            UPI
2         Pending        12       15000   9000.0       Sales  Bank Transfer
3        Rejected        11       25000  27500.0          HR    Credit Card
4         Pending         9        7500   3375.0          IT    Credit Card
5            Paid         9       10000   9000.0     Finance  Bank Transfer
6            Paid        12       25000  36000.0          HR            UPI
7            Paid         2       10000   2000.0     Finance            UPI
8         Pending         2        5000   1000.0  Operations  Bank Transfer
9         Pending         5       15000   7500.0          IT  Bank Transfer
10        Pending        13        2500   1625.0  Operations    Credit Card
11        Pending         8        7500   7200.0     Finance    Credit Card
12           Paid        12       25000  15000.0         NaN    Credit Card
13           Paid         6        7500   5400.0          HR  Bank Transfer
14           Paid         7       25000  17500.0     Finance            UPI
15           Paid         3       25000   9000.0  Operations            UPI
16           Paid         7       15000  12600.0       Sales    Credit Card
17           Paid        12        5000   6000.0       Sales            UPI
18           Paid        12       10000  12000.0     Finance    Credit Card
19           Paid         7       20000   7000.0          IT  Bank Transfer
20           Paid         7       20000  16800.0          IT    Credit Card
21           Paid         8       25000  24000.0          IT  Bank Transfer
22        Pending         4       10000   4000.0       Sales  Bank Transfer
23           Paid        11        2500   2750.0       Sales  Bank Transfer
24           Paid        14        5000   3500.0  Operations    Credit Card
25           Paid        11        2500   3300.0  Operations            UPI
26           Paid        11       25000  13750.0       Sales    Credit Card
27        Pending         4        7500   3000.0  Operations            NaN
28        Pending         8       25000  20000.0          IT  Bank Transfer
29           Paid        14        5000   8400.0          IT  Bank Transfer
30        Pending        14       10000   7000.0          IT  Bank Transfer
31        Pending         3       10000   3000.0          HR  Bank Transfer
32           Paid         6       10000   6000.0          IT    Credit Card
33        Pending         2       20000   4000.0       Sales  Bank Transfer
34           Paid         4        2500   1000.0          HR  Bank Transfer
35           Paid        12        7500  10800.0       Sales    Credit Card
36           Paid        11        7500   8250.0  Operations    Credit Card
37           Paid        12       15000  21600.0          IT  Bank Transfer
38        Pending        14       15000  21000.0  Operations  Bank Transfer
39        Pending        13        2500   3250.0  Operations  Bank Transfer
40           Paid        13       15000  23400.0     Finance  Bank Transfer
41        Pending        10        7500   7500.0     Finance    Credit Card
42        Pending        10        2500   1250.0       Sales            UPI
43           Paid         3        5000    750.0          IT  Bank Transfer
44        Pending         8       20000  16000.0  Operations            UPI
45           Paid         7       25000  17500.0       Sales            UPI
46           Paid         6        2500   1500.0          HR  Bank Transfer
47        Pending         5       10000   2500.0  Operations            UPI
48           Paid         7       10000   3500.0          HR  Bank Transfer
49           Paid         3       10000   3000.0       Sales            UPI
50           Paid         9       10000   4500.0          IT    Credit Card
51           Paid        14       20000  14000.0       Sales    Credit Card
52           Paid         5       20000   5000.0          HR  Bank Transfer
53           Paid        13       20000  13000.0  Operations  Bank Transfer
54           Paid        10        5000   2500.0       Sales    Credit Card
55           Paid         6       15000   9000.0     Finance    Credit Card
56        Pending         1       15000    750.0     Finance  Bank Transfer
57        Pending        11       10000  11000.0          IT  Bank Transfer
58       Rejected         5       10000   6000.0     Finance    Credit Card
59           Paid        13       10000  15600.0          HR            UPI

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Invoice_ID      60 non-null     object
 1   Vendor_Name     60 non-null     object
 2   Invoice_Date    60 non-null     datetime64[ns]
 3   Amount          60 non-null     float64
 4   Category        59 non-null     object
 5   Payment_Status  60 non-null     object
 6   Quantity        60 non-null     int64
 7   Unit_Price      60 non-null     int64
 8   Tax             60 non-null     float64
 9   Department      59 non-null     object
 10  Payment_Method  59 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(2), object(6)
memory usage: 5.3+ KB

In [15]:
df["date"]=df["Invoice_Date"].dt.date
print(df["date"])

0     2026-06-29
1     2026-03-16
2     2026-05-10
3     2026-08-07
4     2026-03-05
5     2026-05-12
6     2026-03-25
7     2026-06-13
8     2026-07-10
9     2026-02-09
10    2026-06-06
11    2026-03-22
12    2026-02-10
13    2026-04-14
14    2026-08-06
15    2026-07-24
16    2026-05-31
17    2026-03-27
18    2026-01-28
19    2026-08-05
20    2026-05-12
21    2026-05-12
22    2026-07-05
23    2026-03-22
24    2026-05-27
25    2026-07-03
26    2026-08-02
27    2026-07-06
28    2026-06-10
29    2026-05-31
30    2026-05-09
31    2026-05-27
32    2026-06-13
33    2026-04-03
34    2026-06-10
35    2026-02-02
36    2026-01-08
37    2026-07-16
38    2026-08-08
39    2026-01-24
40    2026-07-10
41    2026-02-23
42    2026-05-10
43    2026-01-26
44    2026-03-06
45    2026-02-01
46    2026-02-27
47    2026-01-08
48    2026-04-09
49    2026-03-04
50    2026-05-07
51    2026-04-06
52    2026-07-10
53    2026-07-04
54    2026-05-24
55    2026-01-10
56    2026-04-06
57    2026-05-08
58    2026-06-20
59    2026-01-29
Name: date, dtype: object

In [16]:
df["calculated_amount"]=df["Quantity"]*df["Unit_Price"]+df["Tax"]
print(df)

   Invoice_ID          Vendor_Name Invoice_Date    Amount        Category  \
0      INV001    CloudNine Pvt Ltd   2026-06-29  364000.0     Maintenance
1      INV002    CloudNine Pvt Ltd   2026-03-16  184800.0          Travel
2      INV003         DataCore Ltd   2026-05-10  189000.0      Consulting
3      INV004     ABC Technologies   2026-08-07  302500.0      Consulting
4      INV005     Nova Enterprises   2026-03-05   70875.0  Cloud Services
5      INV006     Zenith Solutions   2026-05-12   99000.0        Hardware
6      INV007     Zenith Solutions   2026-03-25  336000.0      Consulting
7      INV008     ABC Technologies   2026-06-13   22000.0          Travel
8      INV009    BlueWave Services   2026-07-10   11000.0        Hardware
9      INV010         DataCore Ltd   2026-02-09   82500.0     Maintenance
10     INV011     ABC Technologies   2026-06-06   34125.0        Software
11     INV012          PQR Systems   2026-03-22   67200.0        Software
12     INV013     Zenith Solutions   2026-02-10  315000.0      Consulting
13     INV014     Nova Enterprises   2026-04-14   50400.0        Software
14     INV015    BlueWave Services   2026-08-06  192500.0  Cloud Services
15     INV016     Nova Enterprises   2026-07-24   84000.0        Software
16     INV017    BlueWave Services   2026-05-31  117600.0  Cloud Services
17     INV018          PQR Systems   2026-03-27   66000.0     Maintenance
18     INV019     Nova Enterprises   2026-01-28  132000.0          Travel
19     INV020     Nova Enterprises   2026-08-05  147000.0        Software
20     INV021     Zenith Solutions   2026-05-12   99000.0        Software
21     INV022     Zenith Solutions   2026-05-12   99000.0          Travel
22     INV023         DataCore Ltd   2026-07-05   44000.0        Hardware
23     INV024  SmartEdge Solutions   2026-03-22   30250.0        Hardware
24     INV025     ABC Technologies   2026-05-27   73500.0      Consulting
25     INV026          PQR Systems   2026-07-03   30800.0          Travel
26     INV027         DataCore Ltd   2026-08-02  288750.0        Software
27     INV028     Nova Enterprises   2026-07-06   33000.0  Cloud Services
28     INV029     Nova Enterprises   2026-06-10  220000.0        Software
29     INV030     Zenith Solutions   2026-05-31   78400.0      Consulting
30     INV031     Zenith Solutions   2026-05-09  147000.0     Maintenance
31     INV032          PQR Systems   2026-05-27   33000.0        Software
32     INV033  SmartEdge Solutions   2026-06-13   66000.0  Cloud Services
33     INV034     ABC Technologies   2026-04-03   44000.0        Hardware
34     INV035     Nova Enterprises   2026-06-10   11000.0     Maintenance
35     INV036  SmartEdge Solutions   2026-02-02  100800.0          Travel
36     INV037         DataCore Ltd   2026-01-08   90750.0     Maintenance
37     INV038  SmartEdge Solutions   2026-07-16  201600.0      Consulting
38     INV039     Nova Enterprises   2026-08-08  231000.0     Maintenance
39     INV040    BlueWave Services   2026-01-24   35750.0     Maintenance
40     INV041     Nova Enterprises   2026-07-10  175000.0        Software
41     INV042     Zenith Solutions   2026-02-23  225000.0        Hardware
42     INV043          PQR Systems   2026-05-10   26250.0        Software
43     INV044    CloudNine Pvt Ltd   2026-01-26   15750.0     Maintenance
44     INV045     Nova Enterprises   2026-03-06  176000.0      Consulting
45     INV046     Zenith Solutions   2026-02-01  192500.0  Cloud Services
46     INV047     Zenith Solutions   2026-02-27   16500.0          Travel
47     INV048     ABC Technologies   2026-01-08   52500.0      Consulting
48     INV049    CloudNine Pvt Ltd   2026-04-09   73500.0             NaN
49     INV050  SmartEdge Solutions   2026-03-04   33000.0        Hardware
50     INV051    CloudNine Pvt Ltd   2026-05-07   94500.0        Software
51     INV052     Zenith Solutions   2026-04-06  294000.0     Maintenance
52     INV053  SmartEdge Solutions   2026-07-10  105000.0  Cloud Services
53     INV054         DataCore Ltd   2026-07-04  273000.0        Software
54     INV055     Nova Enterprises   2026-05-24   52500.0      Consulting
55     INV056     Zenith Solutions   2026-01-10   99000.0      Consulting
56     INV057     Zenith Solutions   2026-04-06   15750.0      Consulting
57     INV058     Nova Enterprises   2026-05-08  121000.0  Cloud Services
58     INV059          PQR Systems   2026-06-20   56000.0        Software
59     INV060     Nova Enterprises   2026-01-29  145600.0          Travel

   Payment_Status  Quantity  Unit_Price      Tax  Department Payment_Method  \
0         Pending        13       25000  39000.0     Finance    Credit Card
1            Paid        11       15000  19800.0  Operations            UPI
2         Pending        12       15000   9000.0       Sales  Bank Transfer
3        Rejected        11       25000  27500.0          HR    Credit Card
4         Pending         9        7500   3375.0          IT    Credit Card
5            Paid         9       10000   9000.0     Finance  Bank Transfer
6            Paid        12       25000  36000.0          HR            UPI
7            Paid         2       10000   2000.0     Finance            UPI
8         Pending         2        5000   1000.0  Operations  Bank Transfer
9         Pending         5       15000   7500.0          IT  Bank Transfer
10        Pending        13        2500   1625.0  Operations    Credit Card
11        Pending         8        7500   7200.0     Finance    Credit Card
12           Paid        12       25000  15000.0         NaN    Credit Card
13           Paid         6        7500   5400.0          HR  Bank Transfer
14           Paid         7       25000  17500.0     Finance            UPI
15           Paid         3       25000   9000.0  Operations            UPI
16           Paid         7       15000  12600.0       Sales    Credit Card
17           Paid        12        5000   6000.0       Sales            UPI
18           Paid        12       10000  12000.0     Finance    Credit Card
19           Paid         7       20000   7000.0          IT  Bank Transfer
20           Paid         7       20000  16800.0          IT    Credit Card
21           Paid         8       25000  24000.0          IT  Bank Transfer
22        Pending         4       10000   4000.0       Sales  Bank Transfer
23           Paid        11        2500   2750.0       Sales  Bank Transfer
24           Paid        14        5000   3500.0  Operations    Credit Card
25           Paid        11        2500   3300.0  Operations            UPI
26           Paid        11       25000  13750.0       Sales    Credit Card
27        Pending         4        7500   3000.0  Operations            NaN
28        Pending         8       25000  20000.0          IT  Bank Transfer
29           Paid        14        5000   8400.0          IT  Bank Transfer
30        Pending        14       10000   7000.0          IT  Bank Transfer
31        Pending         3       10000   3000.0          HR  Bank Transfer
32           Paid         6       10000   6000.0          IT    Credit Card
33        Pending         2       20000   4000.0       Sales  Bank Transfer
34           Paid         4        2500   1000.0          HR  Bank Transfer
35           Paid        12        7500  10800.0       Sales    Credit Card
36           Paid        11        7500   8250.0  Operations    Credit Card
37           Paid        12       15000  21600.0          IT  Bank Transfer
38        Pending        14       15000  21000.0  Operations  Bank Transfer
39        Pending        13        2500   3250.0  Operations  Bank Transfer
40           Paid        13       15000  23400.0     Finance  Bank Transfer
41        Pending        10        7500   7500.0     Finance    Credit Card
42        Pending        10        2500   1250.0       Sales            UPI
43           Paid         3        5000    750.0          IT  Bank Transfer
44        Pending         8       20000  16000.0  Operations            UPI
45           Paid         7       25000  17500.0       Sales            UPI
46           Paid         6        2500   1500.0          HR  Bank Transfer
47        Pending         5       10000   2500.0  Operations            UPI
48           Paid         7       10000   3500.0          HR  Bank Transfer
49           Paid         3       10000   3000.0       Sales            UPI
50           Paid         9       10000   4500.0          IT    Credit Card
51           Paid        14       20000  14000.0       Sales    Credit Card
52           Paid         5       20000   5000.0          HR  Bank Transfer
53           Paid        13       20000  13000.0  Operations  Bank Transfer
54           Paid        10        5000   2500.0       Sales    Credit Card
55           Paid         6       15000   9000.0     Finance    Credit Card
56        Pending         1       15000    750.0     Finance  Bank Transfer
57        Pending        11       10000  11000.0          IT  Bank Transfer
58       Rejected         5       10000   6000.0     Finance    Credit Card
59           Paid        13       10000  15600.0          HR            UPI

          date  calculated_amount
0   2026-06-29           364000.0
1   2026-03-16           184800.0
2   2026-05-10           189000.0
3   2026-08-07           302500.0
4   2026-03-05            70875.0
5   2026-05-12            99000.0
6   2026-03-25           336000.0
7   2026-06-13            22000.0
8   2026-07-10            11000.0
9   2026-02-09            82500.0
10  2026-06-06            34125.0
11  2026-03-22            67200.0
12  2026-02-10           315000.0
13  2026-04-14            50400.0
14  2026-08-06           192500.0
15  2026-07-24            84000.0
16  2026-05-31           117600.0
17  2026-03-27            66000.0
18  2026-01-28           132000.0
19  2026-08-05           147000.0
20  2026-05-12           156800.0
21  2026-05-12           224000.0
22  2026-07-05            44000.0
23  2026-03-22            30250.0
24  2026-05-27            73500.0
25  2026-07-03            30800.0
26  2026-08-02           288750.0
27  2026-07-06            33000.0
28  2026-06-10           220000.0
29  2026-05-31            78400.0
30  2026-05-09           147000.0
31  2026-05-27            33000.0
32  2026-06-13            66000.0
33  2026-04-03            44000.0
34  2026-06-10            11000.0
35  2026-02-02           100800.0
36  2026-01-08            90750.0
37  2026-07-16           201600.0
38  2026-08-08           231000.0
39  2026-01-24            35750.0
40  2026-07-10           218400.0
41  2026-02-23            82500.0
42  2026-05-10            26250.0
43  2026-01-26            15750.0
44  2026-03-06           176000.0
45  2026-02-01           192500.0
46  2026-02-27            16500.0
47  2026-01-08            52500.0
48  2026-04-09            73500.0
49  2026-03-04            33000.0
50  2026-05-07            94500.0
51  2026-04-06           294000.0
52  2026-07-10           105000.0
53  2026-07-04           273000.0
54  2026-05-24            52500.0
55  2026-01-10            99000.0
56  2026-04-06            15750.0
57  2026-05-08           121000.0
58  2026-06-20            56000.0
59  2026-01-29           145600.0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Invoice_ID         60 non-null     object
 1   Vendor_Name        60 non-null     object
 2   Invoice_Date       60 non-null     datetime64[ns]
 3   Amount             60 non-null     float64
 4   Category           59 non-null     object
 5   Payment_Status     60 non-null     object
 6   Quantity           60 non-null     int64
 7   Unit_Price         60 non-null     int64
 8   Tax                60 non-null     float64
 9   Department         59 non-null     object
 10  Payment_Method     59 non-null     object
 11  date               60 non-null     object
 12  calculated_amount  60 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(7)
memory usage: 6.2+ KB

In [18]:
pending_invoice=df[df["Payment_Status"]=="Pending"]
print(pending_invoice)

   Invoice_ID        Vendor_Name Invoice_Date    Amount        Category  \
0      INV001  CloudNine Pvt Ltd   2026-06-29  364000.0     Maintenance
2      INV003       DataCore Ltd   2026-05-10  189000.0      Consulting
4      INV005   Nova Enterprises   2026-03-05   70875.0  Cloud Services
8      INV009  BlueWave Services   2026-07-10   11000.0        Hardware
9      INV010       DataCore Ltd   2026-02-09   82500.0     Maintenance
10     INV011   ABC Technologies   2026-06-06   34125.0        Software
11     INV012        PQR Systems   2026-03-22   67200.0        Software
22     INV023       DataCore Ltd   2026-07-05   44000.0        Hardware
27     INV028   Nova Enterprises   2026-07-06   33000.0  Cloud Services
28     INV029   Nova Enterprises   2026-06-10  220000.0        Software
30     INV031   Zenith Solutions   2026-05-09  147000.0     Maintenance
31     INV032        PQR Systems   2026-05-27   33000.0        Software
33     INV034   ABC Technologies   2026-04-03   44000.0        Hardware
38     INV039   Nova Enterprises   2026-08-08  231000.0     Maintenance
39     INV040  BlueWave Services   2026-01-24   35750.0     Maintenance
41     INV042   Zenith Solutions   2026-02-23  225000.0        Hardware
42     INV043        PQR Systems   2026-05-10   26250.0        Software
44     INV045   Nova Enterprises   2026-03-06  176000.0      Consulting
47     INV048   ABC Technologies   2026-01-08   52500.0      Consulting
56     INV057   Zenith Solutions   2026-04-06   15750.0      Consulting
57     INV058   Nova Enterprises   2026-05-08  121000.0  Cloud Services

   Payment_Status  Quantity  Unit_Price      Tax  Department Payment_Method  \
0         Pending        13       25000  39000.0     Finance    Credit Card
2         Pending        12       15000   9000.0       Sales  Bank Transfer
4         Pending         9        7500   3375.0          IT    Credit Card
8         Pending         2        5000   1000.0  Operations  Bank Transfer
9         Pending         5       15000   7500.0          IT  Bank Transfer
10        Pending        13        2500   1625.0  Operations    Credit Card
11        Pending         8        7500   7200.0     Finance    Credit Card
22        Pending         4       10000   4000.0       Sales  Bank Transfer
27        Pending         4        7500   3000.0  Operations            NaN
28        Pending         8       25000  20000.0          IT  Bank Transfer
30        Pending        14       10000   7000.0          IT  Bank Transfer
31        Pending         3       10000   3000.0          HR  Bank Transfer
33        Pending         2       20000   4000.0       Sales  Bank Transfer
38        Pending        14       15000  21000.0  Operations  Bank Transfer
39        Pending        13        2500   3250.0  Operations  Bank Transfer
41        Pending        10        7500   7500.0     Finance    Credit Card
42        Pending        10        2500   1250.0       Sales            UPI
44        Pending         8       20000  16000.0  Operations            UPI
47        Pending         5       10000   2500.0  Operations            UPI
56        Pending         1       15000    750.0     Finance  Bank Transfer
57        Pending        11       10000  11000.0          IT  Bank Transfer

          date  calculated_amount
0   2026-06-29           364000.0
2   2026-05-10           189000.0
4   2026-03-05            70875.0
8   2026-07-10            11000.0
9   2026-02-09            82500.0
10  2026-06-06            34125.0
11  2026-03-22            67200.0
22  2026-07-05            44000.0
27  2026-07-06            33000.0
28  2026-06-10           220000.0
30  2026-05-09           147000.0
31  2026-05-27            33000.0
33  2026-04-03            44000.0
38  2026-08-08           231000.0
39  2026-01-24            35750.0
41  2026-02-23            82500.0
42  2026-05-10            26250.0
44  2026-03-06           176000.0
47  2026-01-08            52500.0
56  2026-04-06            15750.0
57  2026-05-08           121000.0

In [19]:
it_invoices = df[df["Payment_Status"] == "Pending"]
print(it_invoices)

   Invoice_ID        Vendor_Name Invoice_Date    Amount        Category  \
0      INV001  CloudNine Pvt Ltd   2026-06-29  364000.0     Maintenance
2      INV003       DataCore Ltd   2026-05-10  189000.0      Consulting
4      INV005   Nova Enterprises   2026-03-05   70875.0  Cloud Services
8      INV009  BlueWave Services   2026-07-10   11000.0        Hardware
9      INV010       DataCore Ltd   2026-02-09   82500.0     Maintenance
10     INV011   ABC Technologies   2026-06-06   34125.0        Software
11     INV012        PQR Systems   2026-03-22   67200.0        Software
22     INV023       DataCore Ltd   2026-07-05   44000.0        Hardware
27     INV028   Nova Enterprises   2026-07-06   33000.0  Cloud Services
28     INV029   Nova Enterprises   2026-06-10  220000.0        Software
30     INV031   Zenith Solutions   2026-05-09  147000.0     Maintenance
31     INV032        PQR Systems   2026-05-27   33000.0        Software
33     INV034   ABC Technologies   2026-04-03   44000.0        Hardware
38     INV039   Nova Enterprises   2026-08-08  231000.0     Maintenance
39     INV040  BlueWave Services   2026-01-24   35750.0     Maintenance
41     INV042   Zenith Solutions   2026-02-23  225000.0        Hardware
42     INV043        PQR Systems   2026-05-10   26250.0        Software
44     INV045   Nova Enterprises   2026-03-06  176000.0      Consulting
47     INV048   ABC Technologies   2026-01-08   52500.0      Consulting
56     INV057   Zenith Solutions   2026-04-06   15750.0      Consulting
57     INV058   Nova Enterprises   2026-05-08  121000.0  Cloud Services

   Payment_Status  Quantity  Unit_Price      Tax  Department Payment_Method  \
0         Pending        13       25000  39000.0     Finance    Credit Card
2         Pending        12       15000   9000.0       Sales  Bank Transfer
4         Pending         9        7500   3375.0          IT    Credit Card
8         Pending         2        5000   1000.0  Operations  Bank Transfer
9         Pending         5       15000   7500.0          IT  Bank Transfer
10        Pending        13        2500   1625.0  Operations    Credit Card
11        Pending         8        7500   7200.0     Finance    Credit Card
22        Pending         4       10000   4000.0       Sales  Bank Transfer
27        Pending         4        7500   3000.0  Operations            NaN
28        Pending         8       25000  20000.0          IT  Bank Transfer
30        Pending        14       10000   7000.0          IT  Bank Transfer
31        Pending         3       10000   3000.0          HR  Bank Transfer
33        Pending         2       20000   4000.0       Sales  Bank Transfer
38        Pending        14       15000  21000.0  Operations  Bank Transfer
39        Pending        13        2500   3250.0  Operations  Bank Transfer
41        Pending        10        7500   7500.0     Finance    Credit Card
42        Pending        10        2500   1250.0       Sales            UPI
44        Pending         8       20000  16000.0  Operations            UPI
47        Pending         5       10000   2500.0  Operations            UPI
56        Pending         1       15000    750.0     Finance  Bank Transfer
57        Pending        11       10000  11000.0          IT  Bank Transfer

          date  calculated_amount
0   2026-06-29           364000.0
2   2026-05-10           189000.0
4   2026-03-05            70875.0
8   2026-07-10            11000.0
9   2026-02-09            82500.0
10  2026-06-06            34125.0
11  2026-03-22            67200.0
22  2026-07-05            44000.0
27  2026-07-06            33000.0
28  2026-06-10           220000.0
30  2026-05-09           147000.0
31  2026-05-27            33000.0
33  2026-04-03            44000.0
38  2026-08-08           231000.0
39  2026-01-24            35750.0
41  2026-02-23            82500.0
42  2026-05-10            26250.0
44  2026-03-06           176000.0
47  2026-01-08            52500.0
56  2026-04-06            15750.0
57  2026-05-08           121000.0

In [20]:
high_value=df[df["Amount"]>50000]
print(high_value)

   Invoice_ID          Vendor_Name Invoice_Date    Amount        Category  \
0      INV001    CloudNine Pvt Ltd   2026-06-29  364000.0     Maintenance
1      INV002    CloudNine Pvt Ltd   2026-03-16  184800.0          Travel
2      INV003         DataCore Ltd   2026-05-10  189000.0      Consulting
3      INV004     ABC Technologies   2026-08-07  302500.0      Consulting
4      INV005     Nova Enterprises   2026-03-05   70875.0  Cloud Services
5      INV006     Zenith Solutions   2026-05-12   99000.0        Hardware
6      INV007     Zenith Solutions   2026-03-25  336000.0      Consulting
9      INV010         DataCore Ltd   2026-02-09   82500.0     Maintenance
11     INV012          PQR Systems   2026-03-22   67200.0        Software
12     INV013     Zenith Solutions   2026-02-10  315000.0      Consulting
13     INV014     Nova Enterprises   2026-04-14   50400.0        Software
14     INV015    BlueWave Services   2026-08-06  192500.0  Cloud Services
15     INV016     Nova Enterprises   2026-07-24   84000.0        Software
16     INV017    BlueWave Services   2026-05-31  117600.0  Cloud Services
17     INV018          PQR Systems   2026-03-27   66000.0     Maintenance
18     INV019     Nova Enterprises   2026-01-28  132000.0          Travel
19     INV020     Nova Enterprises   2026-08-05  147000.0        Software
20     INV021     Zenith Solutions   2026-05-12   99000.0        Software
21     INV022     Zenith Solutions   2026-05-12   99000.0          Travel
24     INV025     ABC Technologies   2026-05-27   73500.0      Consulting
26     INV027         DataCore Ltd   2026-08-02  288750.0        Software
28     INV029     Nova Enterprises   2026-06-10  220000.0        Software
29     INV030     Zenith Solutions   2026-05-31   78400.0      Consulting
30     INV031     Zenith Solutions   2026-05-09  147000.0     Maintenance
32     INV033  SmartEdge Solutions   2026-06-13   66000.0  Cloud Services
35     INV036  SmartEdge Solutions   2026-02-02  100800.0          Travel
36     INV037         DataCore Ltd   2026-01-08   90750.0     Maintenance
37     INV038  SmartEdge Solutions   2026-07-16  201600.0      Consulting
38     INV039     Nova Enterprises   2026-08-08  231000.0     Maintenance
40     INV041     Nova Enterprises   2026-07-10  175000.0        Software
41     INV042     Zenith Solutions   2026-02-23  225000.0        Hardware
44     INV045     Nova Enterprises   2026-03-06  176000.0      Consulting
45     INV046     Zenith Solutions   2026-02-01  192500.0  Cloud Services
47     INV048     ABC Technologies   2026-01-08   52500.0      Consulting
48     INV049    CloudNine Pvt Ltd   2026-04-09   73500.0             NaN
50     INV051    CloudNine Pvt Ltd   2026-05-07   94500.0        Software
51     INV052     Zenith Solutions   2026-04-06  294000.0     Maintenance
52     INV053  SmartEdge Solutions   2026-07-10  105000.0  Cloud Services
53     INV054         DataCore Ltd   2026-07-04  273000.0        Software
54     INV055     Nova Enterprises   2026-05-24   52500.0      Consulting
55     INV056     Zenith Solutions   2026-01-10   99000.0      Consulting
57     INV058     Nova Enterprises   2026-05-08  121000.0  Cloud Services
58     INV059          PQR Systems   2026-06-20   56000.0        Software
59     INV060     Nova Enterprises   2026-01-29  145600.0          Travel

   Payment_Status  Quantity  Unit_Price      Tax  Department Payment_Method  \
0         Pending        13       25000  39000.0     Finance    Credit Card
1            Paid        11       15000  19800.0  Operations            UPI
2         Pending        12       15000   9000.0       Sales  Bank Transfer
3        Rejected        11       25000  27500.0          HR    Credit Card
4         Pending         9        7500   3375.0          IT    Credit Card
5            Paid         9       10000   9000.0     Finance  Bank Transfer
6            Paid        12       25000  36000.0          HR            UPI
9         Pending         5       15000   7500.0          IT  Bank Transfer
11        Pending         8        7500   7200.0     Finance    Credit Card
12           Paid        12       25000  15000.0         NaN    Credit Card
13           Paid         6        7500   5400.0          HR  Bank Transfer
14           Paid         7       25000  17500.0     Finance            UPI
15           Paid         3       25000   9000.0  Operations            UPI
16           Paid         7       15000  12600.0       Sales    Credit Card
17           Paid        12        5000   6000.0       Sales            UPI
18           Paid        12       10000  12000.0     Finance    Credit Card
19           Paid         7       20000   7000.0          IT  Bank Transfer
20           Paid         7       20000  16800.0          IT    Credit Card
21           Paid         8       25000  24000.0          IT  Bank Transfer
24           Paid        14        5000   3500.0  Operations    Credit Card
26           Paid        11       25000  13750.0       Sales    Credit Card
28        Pending         8       25000  20000.0          IT  Bank Transfer
29           Paid        14        5000   8400.0          IT  Bank Transfer
30        Pending        14       10000   7000.0          IT  Bank Transfer
32           Paid         6       10000   6000.0          IT    Credit Card
35           Paid        12        7500  10800.0       Sales    Credit Card
36           Paid        11        7500   8250.0  Operations    Credit Card
37           Paid        12       15000  21600.0          IT  Bank Transfer
38        Pending        14       15000  21000.0  Operations  Bank Transfer
40           Paid        13       15000  23400.0     Finance  Bank Transfer
41        Pending        10        7500   7500.0     Finance    Credit Card
44        Pending         8       20000  16000.0  Operations            UPI
45           Paid         7       25000  17500.0       Sales            UPI
47        Pending         5       10000   2500.0  Operations            UPI
48           Paid         7       10000   3500.0          HR  Bank Transfer
50           Paid         9       10000   4500.0          IT    Credit Card
51           Paid        14       20000  14000.0       Sales    Credit Card
52           Paid         5       20000   5000.0          HR  Bank Transfer
53           Paid        13       20000  13000.0  Operations  Bank Transfer
54           Paid        10        5000   2500.0       Sales    Credit Card
55           Paid         6       15000   9000.0     Finance    Credit Card
57        Pending        11       10000  11000.0          IT  Bank Transfer
58       Rejected         5       10000   6000.0     Finance    Credit Card
59           Paid        13       10000  15600.0          HR            UPI

          date  calculated_amount
0   2026-06-29           364000.0
1   2026-03-16           184800.0
2   2026-05-10           189000.0
3   2026-08-07           302500.0
4   2026-03-05            70875.0
5   2026-05-12            99000.0
6   2026-03-25           336000.0
9   2026-02-09            82500.0
11  2026-03-22            67200.0
12  2026-02-10           315000.0
13  2026-04-14            50400.0
14  2026-08-06           192500.0
15  2026-07-24            84000.0
16  2026-05-31           117600.0
17  2026-03-27            66000.0
18  2026-01-28           132000.0
19  2026-08-05           147000.0
20  2026-05-12           156800.0
21  2026-05-12           224000.0
24  2026-05-27            73500.0
26  2026-08-02           288750.0
28  2026-06-10           220000.0
29  2026-05-31            78400.0
30  2026-05-09           147000.0
32  2026-06-13            66000.0
35  2026-02-02           100800.0
36  2026-01-08            90750.0
37  2026-07-16           201600.0
38  2026-08-08           231000.0
40  2026-07-10           218400.0
41  2026-02-23            82500.0
44  2026-03-06           176000.0
45  2026-02-01           192500.0
47  2026-01-08            52500.0
48  2026-04-09            73500.0
50  2026-05-07            94500.0
51  2026-04-06           294000.0
52  2026-07-10           105000.0
53  2026-07-04           273000.0
54  2026-05-24            52500.0
55  2026-01-10            99000.0
57  2026-05-08           121000.0
58  2026-06-20            56000.0
59  2026-01-29           145600.0

In [21]:
IT=df[df["Department"]=="IT"]
print(IT)

   Invoice_ID          Vendor_Name Invoice_Date    Amount        Category  \
4      INV005     Nova Enterprises   2026-03-05   70875.0  Cloud Services
9      INV010         DataCore Ltd   2026-02-09   82500.0     Maintenance
19     INV020     Nova Enterprises   2026-08-05  147000.0        Software
20     INV021     Zenith Solutions   2026-05-12   99000.0        Software
21     INV022     Zenith Solutions   2026-05-12   99000.0          Travel
28     INV029     Nova Enterprises   2026-06-10  220000.0        Software
29     INV030     Zenith Solutions   2026-05-31   78400.0      Consulting
30     INV031     Zenith Solutions   2026-05-09  147000.0     Maintenance
32     INV033  SmartEdge Solutions   2026-06-13   66000.0  Cloud Services
37     INV038  SmartEdge Solutions   2026-07-16  201600.0      Consulting
43     INV044    CloudNine Pvt Ltd   2026-01-26   15750.0     Maintenance
50     INV051    CloudNine Pvt Ltd   2026-05-07   94500.0        Software
57     INV058     Nova Enterprises   2026-05-08  121000.0  Cloud Services

   Payment_Status  Quantity  Unit_Price      Tax Department Payment_Method  \
4         Pending         9        7500   3375.0         IT    Credit Card
9         Pending         5       15000   7500.0         IT  Bank Transfer
19           Paid         7       20000   7000.0         IT  Bank Transfer
20           Paid         7       20000  16800.0         IT    Credit Card
21           Paid         8       25000  24000.0         IT  Bank Transfer
28        Pending         8       25000  20000.0         IT  Bank Transfer
29           Paid        14        5000   8400.0         IT  Bank Transfer
30        Pending        14       10000   7000.0         IT  Bank Transfer
32           Paid         6       10000   6000.0         IT    Credit Card
37           Paid        12       15000  21600.0         IT  Bank Transfer
43           Paid         3        5000    750.0         IT  Bank Transfer
50           Paid         9       10000   4500.0         IT    Credit Card
57        Pending        11       10000  11000.0         IT  Bank Transfer

          date  calculated_amount
4   2026-03-05            70875.0
9   2026-02-09            82500.0
19  2026-08-05           147000.0
20  2026-05-12           156800.0
21  2026-05-12           224000.0
28  2026-06-10           220000.0
29  2026-05-31            78400.0
30  2026-05-09           147000.0
32  2026-06-13            66000.0
37  2026-07-16           201600.0
43  2026-01-26            15750.0
50  2026-05-07            94500.0
57  2026-05-08           121000.0

In [22]:
mul_con=df[(df['Payment_Status']=="Pending") & (df['Amount']>50000)]
print(mul_con)

   Invoice_ID        Vendor_Name Invoice_Date    Amount        Category  \
0      INV001  CloudNine Pvt Ltd   2026-06-29  364000.0     Maintenance
2      INV003       DataCore Ltd   2026-05-10  189000.0      Consulting
4      INV005   Nova Enterprises   2026-03-05   70875.0  Cloud Services
9      INV010       DataCore Ltd   2026-02-09   82500.0     Maintenance
11     INV012        PQR Systems   2026-03-22   67200.0        Software
28     INV029   Nova Enterprises   2026-06-10  220000.0        Software
30     INV031   Zenith Solutions   2026-05-09  147000.0     Maintenance
38     INV039   Nova Enterprises   2026-08-08  231000.0     Maintenance
41     INV042   Zenith Solutions   2026-02-23  225000.0        Hardware
44     INV045   Nova Enterprises   2026-03-06  176000.0      Consulting
47     INV048   ABC Technologies   2026-01-08   52500.0      Consulting
57     INV058   Nova Enterprises   2026-05-08  121000.0  Cloud Services

   Payment_Status  Quantity  Unit_Price      Tax  Department Payment_Method  \
0         Pending        13       25000  39000.0     Finance    Credit Card
2         Pending        12       15000   9000.0       Sales  Bank Transfer
4         Pending         9        7500   3375.0          IT    Credit Card
9         Pending         5       15000   7500.0          IT  Bank Transfer
11        Pending         8        7500   7200.0     Finance    Credit Card
28        Pending         8       25000  20000.0          IT  Bank Transfer
30        Pending        14       10000   7000.0          IT  Bank Transfer
38        Pending        14       15000  21000.0  Operations  Bank Transfer
41        Pending        10        7500   7500.0     Finance    Credit Card
44        Pending         8       20000  16000.0  Operations            UPI
47        Pending         5       10000   2500.0  Operations            UPI
57        Pending        11       10000  11000.0          IT  Bank Transfer

          date  calculated_amount
0   2026-06-29           364000.0
2   2026-05-10           189000.0
4   2026-03-05            70875.0
9   2026-02-09            82500.0
11  2026-03-22            67200.0
28  2026-06-10           220000.0
30  2026-05-09           147000.0
38  2026-08-08           231000.0
41  2026-02-23            82500.0
44  2026-03-06           176000.0
47  2026-01-08            52500.0
57  2026-05-08           121000.0

In [23]:
mul_cons=df[(df['Payment_Status']=="Paid") | (df['Amount']=="Rejected")]
print(mul_cons)

   Invoice_ID          Vendor_Name Invoice_Date    Amount        Category  \
1      INV002    CloudNine Pvt Ltd   2026-03-16  184800.0          Travel
5      INV006     Zenith Solutions   2026-05-12   99000.0        Hardware
6      INV007     Zenith Solutions   2026-03-25  336000.0      Consulting
7      INV008     ABC Technologies   2026-06-13   22000.0          Travel
12     INV013     Zenith Solutions   2026-02-10  315000.0      Consulting
13     INV014     Nova Enterprises   2026-04-14   50400.0        Software
14     INV015    BlueWave Services   2026-08-06  192500.0  Cloud Services
15     INV016     Nova Enterprises   2026-07-24   84000.0        Software
16     INV017    BlueWave Services   2026-05-31  117600.0  Cloud Services
17     INV018          PQR Systems   2026-03-27   66000.0     Maintenance
18     INV019     Nova Enterprises   2026-01-28  132000.0          Travel
19     INV020     Nova Enterprises   2026-08-05  147000.0        Software
20     INV021     Zenith Solutions   2026-05-12   99000.0        Software
21     INV022     Zenith Solutions   2026-05-12   99000.0          Travel
23     INV024  SmartEdge Solutions   2026-03-22   30250.0        Hardware
24     INV025     ABC Technologies   2026-05-27   73500.0      Consulting
25     INV026          PQR Systems   2026-07-03   30800.0          Travel
26     INV027         DataCore Ltd   2026-08-02  288750.0        Software
29     INV030     Zenith Solutions   2026-05-31   78400.0      Consulting
32     INV033  SmartEdge Solutions   2026-06-13   66000.0  Cloud Services
34     INV035     Nova Enterprises   2026-06-10   11000.0     Maintenance
35     INV036  SmartEdge Solutions   2026-02-02  100800.0          Travel
36     INV037         DataCore Ltd   2026-01-08   90750.0     Maintenance
37     INV038  SmartEdge Solutions   2026-07-16  201600.0      Consulting
40     INV041     Nova Enterprises   2026-07-10  175000.0        Software
43     INV044    CloudNine Pvt Ltd   2026-01-26   15750.0     Maintenance
45     INV046     Zenith Solutions   2026-02-01  192500.0  Cloud Services
46     INV047     Zenith Solutions   2026-02-27   16500.0          Travel
48     INV049    CloudNine Pvt Ltd   2026-04-09   73500.0             NaN
49     INV050  SmartEdge Solutions   2026-03-04   33000.0        Hardware
50     INV051    CloudNine Pvt Ltd   2026-05-07   94500.0        Software
51     INV052     Zenith Solutions   2026-04-06  294000.0     Maintenance
52     INV053  SmartEdge Solutions   2026-07-10  105000.0  Cloud Services
53     INV054         DataCore Ltd   2026-07-04  273000.0        Software
54     INV055     Nova Enterprises   2026-05-24   52500.0      Consulting
55     INV056     Zenith Solutions   2026-01-10   99000.0      Consulting
59     INV060     Nova Enterprises   2026-01-29  145600.0          Travel

   Payment_Status  Quantity  Unit_Price      Tax  Department Payment_Method  \
1            Paid        11       15000  19800.0  Operations            UPI
5            Paid         9       10000   9000.0     Finance  Bank Transfer
6            Paid        12       25000  36000.0          HR            UPI
7            Paid         2       10000   2000.0     Finance            UPI
12           Paid        12       25000  15000.0         NaN    Credit Card
13           Paid         6        7500   5400.0          HR  Bank Transfer
14           Paid         7       25000  17500.0     Finance            UPI
15           Paid         3       25000   9000.0  Operations            UPI
16           Paid         7       15000  12600.0       Sales    Credit Card
17           Paid        12        5000   6000.0       Sales            UPI
18           Paid        12       10000  12000.0     Finance    Credit Card
19           Paid         7       20000   7000.0          IT  Bank Transfer
20           Paid         7       20000  16800.0          IT    Credit Card
21           Paid         8       25000  24000.0          IT  Bank Transfer
23           Paid        11        2500   2750.0       Sales  Bank Transfer
24           Paid        14        5000   3500.0  Operations    Credit Card
25           Paid        11        2500   3300.0  Operations            UPI
26           Paid        11       25000  13750.0       Sales    Credit Card
29           Paid        14        5000   8400.0          IT  Bank Transfer
32           Paid         6       10000   6000.0          IT    Credit Card
34           Paid         4        2500   1000.0          HR  Bank Transfer
35           Paid        12        7500  10800.0       Sales    Credit Card
36           Paid        11        7500   8250.0  Operations    Credit Card
37           Paid        12       15000  21600.0          IT  Bank Transfer
40           Paid        13       15000  23400.0     Finance  Bank Transfer
43           Paid         3        5000    750.0          IT  Bank Transfer
45           Paid         7       25000  17500.0       Sales            UPI
46           Paid         6        2500   1500.0          HR  Bank Transfer
48           Paid         7       10000   3500.0          HR  Bank Transfer
49           Paid         3       10000   3000.0       Sales            UPI
50           Paid         9       10000   4500.0          IT    Credit Card
51           Paid        14       20000  14000.0       Sales    Credit Card
52           Paid         5       20000   5000.0          HR  Bank Transfer
53           Paid        13       20000  13000.0  Operations  Bank Transfer
54           Paid        10        5000   2500.0       Sales    Credit Card
55           Paid         6       15000   9000.0     Finance    Credit Card
59           Paid        13       10000  15600.0          HR            UPI

          date  calculated_amount
1   2026-03-16           184800.0
5   2026-05-12            99000.0
6   2026-03-25           336000.0
7   2026-06-13            22000.0
12  2026-02-10           315000.0
13  2026-04-14            50400.0
14  2026-08-06           192500.0
15  2026-07-24            84000.0
16  2026-05-31           117600.0
17  2026-03-27            66000.0
18  2026-01-28           132000.0
19  2026-08-05           147000.0
20  2026-05-12           156800.0
21  2026-05-12           224000.0
23  2026-03-22            30250.0
24  2026-05-27            73500.0
25  2026-07-03            30800.0
26  2026-08-02           288750.0
29  2026-05-31            78400.0
32  2026-06-13            66000.0
34  2026-06-10            11000.0
35  2026-02-02           100800.0
36  2026-01-08            90750.0
37  2026-07-16           201600.0
40  2026-07-10           218400.0
43  2026-01-26            15750.0
45  2026-02-01           192500.0
46  2026-02-27            16500.0
48  2026-04-09            73500.0
49  2026-03-04            33000.0
50  2026-05-07            94500.0
51  2026-04-06           294000.0
52  2026-07-10           105000.0
53  2026-07-04           273000.0
54  2026-05-24            52500.0
55  2026-01-10            99000.0
59  2026-01-29           145600.0

In [24]:
df.duplicated(subset=["Vendor_Name","Amount","Invoice_Date"],keep=False)

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21     True
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
dtype: bool

In [25]:
invoice_amount=df.groupby("Vendor_Name")["Amount"].sum()
print(invoice_amount)

Vendor_Name
ABC Technologies        528625.0
BlueWave Services       356850.0
CloudNine Pvt Ltd       732550.0
DataCore Ltd            968000.0
Nova Enterprises       1649375.0
PQR Systems             279250.0
SmartEdge Solutions     536650.0
Zenith Solutions       2016150.0
Name: Amount, dtype: float64

In [26]:
aggregate=df.groupby("Vendor_Name")["Amount"].agg(["min","max","sum","count"])
print(aggregate)

                         min       max        sum  count
Vendor_Name
ABC Technologies     22000.0  302500.0   528625.0      6
BlueWave Services    11000.0  192500.0   356850.0      4
CloudNine Pvt Ltd    15750.0  364000.0   732550.0      5
DataCore Ltd         44000.0  288750.0   968000.0      6
Nova Enterprises     11000.0  231000.0  1649375.0     14
PQR Systems          26250.0   67200.0   279250.0      6
SmartEdge Solutions  30250.0  201600.0   536650.0      6
Zenith Solutions     15750.0  336000.0  2016150.0     13

In [27]:
status=df.groupby("Payment_Status")["Amount"].agg(["sum","count","mean"])
print(status)

                      sum  count           mean
Payment_Status
Paid            4486000.0     37  121243.243243
Pending         2222950.0     21  105854.761905
Rejected         358500.0      2  179250.000000

In [28]:
#condition for suspicious invoice
high_value=df[df["Amount"]>100000]
print(high_value)

   Invoice_ID          Vendor_Name Invoice_Date    Amount        Category  \
0      INV001    CloudNine Pvt Ltd   2026-06-29  364000.0     Maintenance
1      INV002    CloudNine Pvt Ltd   2026-03-16  184800.0          Travel
2      INV003         DataCore Ltd   2026-05-10  189000.0      Consulting
3      INV004     ABC Technologies   2026-08-07  302500.0      Consulting
6      INV007     Zenith Solutions   2026-03-25  336000.0      Consulting
12     INV013     Zenith Solutions   2026-02-10  315000.0      Consulting
14     INV015    BlueWave Services   2026-08-06  192500.0  Cloud Services
16     INV017    BlueWave Services   2026-05-31  117600.0  Cloud Services
18     INV019     Nova Enterprises   2026-01-28  132000.0          Travel
19     INV020     Nova Enterprises   2026-08-05  147000.0        Software
26     INV027         DataCore Ltd   2026-08-02  288750.0        Software
28     INV029     Nova Enterprises   2026-06-10  220000.0        Software
30     INV031     Zenith Solutions   2026-05-09  147000.0     Maintenance
35     INV036  SmartEdge Solutions   2026-02-02  100800.0          Travel
37     INV038  SmartEdge Solutions   2026-07-16  201600.0      Consulting
38     INV039     Nova Enterprises   2026-08-08  231000.0     Maintenance
40     INV041     Nova Enterprises   2026-07-10  175000.0        Software
41     INV042     Zenith Solutions   2026-02-23  225000.0        Hardware
44     INV045     Nova Enterprises   2026-03-06  176000.0      Consulting
45     INV046     Zenith Solutions   2026-02-01  192500.0  Cloud Services
51     INV052     Zenith Solutions   2026-04-06  294000.0     Maintenance
52     INV053  SmartEdge Solutions   2026-07-10  105000.0  Cloud Services
53     INV054         DataCore Ltd   2026-07-04  273000.0        Software
57     INV058     Nova Enterprises   2026-05-08  121000.0  Cloud Services
59     INV060     Nova Enterprises   2026-01-29  145600.0          Travel

   Payment_Status  Quantity  Unit_Price      Tax  Department Payment_Method  \
0         Pending        13       25000  39000.0     Finance    Credit Card
1            Paid        11       15000  19800.0  Operations            UPI
2         Pending        12       15000   9000.0       Sales  Bank Transfer
3        Rejected        11       25000  27500.0          HR    Credit Card
6            Paid        12       25000  36000.0          HR            UPI
12           Paid        12       25000  15000.0         NaN    Credit Card
14           Paid         7       25000  17500.0     Finance            UPI
16           Paid         7       15000  12600.0       Sales    Credit Card
18           Paid        12       10000  12000.0     Finance    Credit Card
19           Paid         7       20000   7000.0          IT  Bank Transfer
26           Paid        11       25000  13750.0       Sales    Credit Card
28        Pending         8       25000  20000.0          IT  Bank Transfer
30        Pending        14       10000   7000.0          IT  Bank Transfer
35           Paid        12        7500  10800.0       Sales    Credit Card
37           Paid        12       15000  21600.0          IT  Bank Transfer
38        Pending        14       15000  21000.0  Operations  Bank Transfer
40           Paid        13       15000  23400.0     Finance  Bank Transfer
41        Pending        10        7500   7500.0     Finance    Credit Card
44        Pending         8       20000  16000.0  Operations            UPI
45           Paid         7       25000  17500.0       Sales            UPI
51           Paid        14       20000  14000.0       Sales    Credit Card
52           Paid         5       20000   5000.0          HR  Bank Transfer
53           Paid        13       20000  13000.0  Operations  Bank Transfer
57        Pending        11       10000  11000.0          IT  Bank Transfer
59           Paid        13       10000  15600.0          HR            UPI

          date  calculated_amount
0   2026-06-29           364000.0
1   2026-03-16           184800.0
2   2026-05-10           189000.0
3   2026-08-07           302500.0
6   2026-03-25           336000.0
12  2026-02-10           315000.0
14  2026-08-06           192500.0
16  2026-05-31           117600.0
18  2026-01-28           132000.0
19  2026-08-05           147000.0
26  2026-08-02           288750.0
28  2026-06-10           220000.0
30  2026-05-09           147000.0
35  2026-02-02           100800.0
37  2026-07-16           201600.0
38  2026-08-08           231000.0
40  2026-07-10           218400.0
41  2026-02-23            82500.0
44  2026-03-06           176000.0
45  2026-02-01           192500.0
51  2026-04-06           294000.0
52  2026-07-10           105000.0
53  2026-07-04           273000.0
57  2026-05-08           121000.0
59  2026-01-29           145600.0

In [29]:
#suspicious conditin<10000 & duplicated invoice & pending invoices
suspicious_invoices=df[(df["Amount"] < 100000) & (df["Payment_Status"] == "Pending")]
display(suspicious_invoices)

,Invoice_ID,Vendor_Name,Invoice_Date,Amount,Category,Payment_Status,Quantity,Unit_Price,Tax,Department,Payment_Method,date,calculated_amount
4,INV005,Nova Enterprises,2026-03-05,70875.0,Cloud Services,Pending,9,7500,3375.0,IT,Credit Card,2026-03-05,70875.0
8,INV009,BlueWave Services,2026-07-10,11000.0,Hardware,Pending,2,5000,1000.0,Operations,Bank Transfer,2026-07-10,11000.0
9,INV010,DataCore Ltd,2026-02-09,82500.0,Maintenance,Pending,5,15000,7500.0,IT,Bank Transfer,2026-02-09,82500.0
10,INV011,ABC Technologies,2026-06-06,34125.0,Software,Pending,13,2500,1625.0,Operations,Credit Card,2026-06-06,34125.0
11,INV012,PQR Systems,2026-03-22,67200.0,Software,Pending,8,7500,7200.0,Finance,Credit Card,2026-03-22,67200.0
22,INV023,DataCore Ltd,2026-07-05,44000.0,Hardware,Pending,4,10000,4000.0,Sales,Bank Transfer,2026-07-05,44000.0
27,INV028,Nova Enterprises,2026-07-06,33000.0,Cloud Services,Pending,4,7500,3000.0,Operations,NaN,2026-07-06,33000.0
31,INV032,PQR Systems,2026-05-27,33000.0,Software,Pending,3,10000,3000.0,HR,Bank Transfer,2026-05-27,33000.0
33,INV034,ABC Technologies,2026-04-03,44000.0,Hardware,Pending,2,20000,4000.0,Sales,Bank Transfer,2026-04-03,44000.0
39,INV040,BlueWave Services,2026-01-24,35750.0,Maintenance,Pending,13,2500,3250.0,Operations,Bank Transfer,2026-01-24,35750.0
42,INV043,PQR Systems,2026-05-10,26250.0,Software,Pending,10,2500,1250.0,Sales,UPI,2026-05-10,26250.0
47,INV048,ABC Technologies,2026-01-08,52500.0,Consulting,Pending,5,10000,2500.0,Operations,UPI,2026-01-08,52500.0
56,INV057,Zenith Solutions,2026-04-06,15750.0,Consulting,Pending,1,15000,750.0,Finance,Bank Transfer,2026-04-06,15750.0